const std = @import("std");

const model = @import("model.zig");
const render = @import("render.zig");

const Allocator = std.mem.Allocator;
const Message = model.Message;
const Model = model.Model;
const Writer = std.Io.Writer;
const assert = std.debug.assert;

pub const Error = Allocator.Error || render.Error;

const MessageInfoLiteral = struct {
    global_number: u16,
    name: []const u8,
    fields: render.Verbatim,
};

const profile_import = "profile";

const fields_suffix = "_fields";
const info_suffix = "_info";

const banner =
    "//! Generated by tools/generate_profile.zig from tools/Profile.xlsx; do not edit.\n" ++
    "//! Regenerate with `zig build profile`; `zig build test` fails if this file is stale.\n\n";

const validation_branch_quota = 1_000_000;

comptime {
    assert(profile_import.len > 0);
    assert(fields_suffix.len > 0);
    assert(info_suffix.len > 0);
}

pub fn types_file(arena: Allocator, profile: *const Model) Error![]const u8 {
    assert(profile.types.len > 0);

    var out: Writer.Allocating = .init(arena);
    const writer = &out.writer;

    try writer.writeAll(banner);
    try writer.writeAll("pub const TypeId = enum {\n");

    for (profile.types) |table| {
        assert(table.name.len > 0);

        try writer.print("    {f},\n", .{std.zig.fmtId(table.name)});
    }

    try writer.writeAll("};\n\n");
    try writer.writeAll("pub fn type_value_name(type_id: TypeId, value: u64) ?[]const u8 {\n");
    try writer.writeAll("    return switch (type_id) {\n");

    for (profile.types) |table| {
        try write_type_prong(writer, table);
    }

    try writer.writeAll("    };\n}\n");

    assert(out.writer.buffered().len > 0);

    return out.writer.buffered();
}

fn write_type_prong(writer: *Writer, table: model.TypeTable) Error!void {
    assert(table.name.len > 0);
    assert(table.values.len > 0);

    try writer.print("        .{f} => switch (value) {{\n", .{std.zig.fmtId(table.name)});

    for (table.values) |value| {
        assert(value.name.len > 0);
        assert(value.number >= 0);

        const name = std.zig.fmtString(value.name);

        try writer.print("            {d} => \"{f}\",\n", .{ value.number, name });
    }

    try writer.writeAll("            else => null,\n        },\n");
}

pub fn messages_file(arena: Allocator, profile: *const Model) Error![]const u8 {
    assert(profile.messages.len > 0);

    var out: Writer.Allocating = .init(arena);
    const writer = &out.writer;

    try writer.writeAll(banner);
    try writer.writeAll("const std = @import(\"std\");\n\n");
    try writer.print("const {s} = @import(\"../profile.zig\");\n", .{profile_import});
    try writer.writeAll("const BaseType = @import(\"../decoder.zig\").BaseType;\n");
    try writer.writeAll("const TypeId = @import(\"types.zig\").TypeId;\n\n");
    try writer.writeAll("const assert = std.debug.assert;\n\n");

    for (profile.messages) |message| {
        try write_field_table(writer, message);
    }

    for (profile.messages) |message| {
        try write_message_info(arena, writer, message);
    }

    try write_infos_table(writer, profile.messages);
    try write_lookup(writer, profile.messages);
    try write_validation(writer);

    assert(out.writer.buffered().len > 0);

    return out.writer.buffered();
}

fn write_field_table(writer: *Writer, message: Message) Error!void {
    assert(message.name.len > 0);

    try writer.print("const {s}{s} = [_]{s}.FieldInfo{{\n", .{
        message.name,
        fields_suffix,
        profile_import,
    });

    for (message.fields) |field| {
        assert(field.name.len > 0);
        assert(field.scale != 0.0);

        try writer.writeAll("    ");
        try render.value(writer, field);
        try writer.writeAll(",\n");
    }

    try writer.writeAll("};\n\n");
}

fn write_message_info(arena: Allocator, writer: *Writer, message: Message) Error!void {
    assert(message.name.len > 0);

    const reference = try std.fmt.allocPrint(arena, "&{s}{s}", .{ message.name, fields_suffix });

    assert(reference.len == message.name.len + fields_suffix.len + 1);
    assert(reference[0] == '&');

    const literal = MessageInfoLiteral{
        .global_number = message.global_number,
        .name = message.name,
        .fields = .{ .text = reference },
    };

    try writer.print("const {s}{s} = {s}.MessageInfo", .{
        message.name,
        info_suffix,
        profile_import,
    });

    try render.structure_body(writer, literal);
    try writer.writeAll(";\n");
}

fn write_infos_table(writer: *Writer, messages: []const Message) Error!void {
    assert(messages.len > 0);

    try writer.print(
        "\nconst message_infos = [_]*const {s}.MessageInfo{{\n",
        .{profile_import},
    );

    for (messages) |message| {
        try writer.print("    &{s}{s},\n", .{ message.name, info_suffix });
    }

    try writer.writeAll("};\n");
}

fn write_validation(writer: *Writer) Error!void {
    try writer.print("\ncomptime {{\n    @setEvalBranchQuota({d});\n\n", .{
        validation_branch_quota,
    });

    try writer.writeAll(
        \\    for (&message_infos) |info| {
        \\        assert(info.name.len > 0);
        \\        assert(message_info(info.global_number).?.global_number == info.global_number);
        \\
        \\        for (info.fields) |field| {
        \\            assert(field.name.len > 0);
        \\            assert(field.scale != 0.0);
        \\            assert(std.math.isFinite(field.scale));
        \\            assert(std.math.isFinite(field.offset));
        \\
        \\            for (field.subfields) |subfield| {
        \\                assert(subfield.name.len > 0);
        \\                assert(subfield.scale != 0.0);
        \\                assert(subfield.reference_value >= 0);
        \\            }
        \\
        \\            for (field.components) |component| {
        \\                assert(component.scale != 0.0);
        \\                assert(std.math.isFinite(component.offset));
        \\            }
        \\        }
        \\    }
        \\}
        \\
    );
}

fn write_lookup(writer: *Writer, messages: []const Message) Error!void {
    assert(messages.len > 0);

    try writer.print(
        "\npub fn message_info(global_number: u16) ?*const {s}.MessageInfo {{\n",
        .{profile_import},
    );

    try writer.writeAll("    return switch (global_number) {\n");

    var seen = std.StaticBitSet(std.math.maxInt(u16) + 1).initEmpty();
    var written: u32 = 0;

    for (messages) |message| {
        if (seen.isSet(message.global_number)) continue;

        seen.set(message.global_number);
        written += 1;

        assert(seen.isSet(message.global_number));
        assert(written <= messages.len);

        try writer.print("        {d} => &{s}{s},\n", .{
            message.global_number,
            message.name,
            info_suffix,
        });
    }

    assert(written >= 1);
    assert(written <= messages.len);
    assert(seen.count() == written);

    try writer.writeAll("        else => null,\n    };\n}\n");
}
